enum actionTypes {
  LOADING = "PURCHASE_PENDING",
  CLEAR_LOADING = "CLEAR_LOADING",
  GET_BRAND_ID = "GET_BRAND_ID",
  GET_MODEL_ID = "GET_MODEL_ID",
  CREATE_PURCHASE_ENTRY = "CREATE_PURCHASE_ENTRY",
  GET_PURCHASE = "GET_PURCHASE",
  GET_INVENTORY_NAME = "GET_INVENTORY_NAME",
}
export default actionTypes;
