enum actionTypes {
  GET_USER_PENDING = "GET_USER_PENDING",
  GET_USER_SUCCESS = "GET_USER_SUCCESS",
  GET_USER_FAILED = "GET_USER_FAILED",

  ADD_USER_PENDING = "ADD_USER_PENDING",
  ADD_USER_SUCCESS = "ADD_USER_SUCCESS",
  ADD_USER_FAILED = "ADD_USER_FAILED",
}
export default actionTypes;
