enum actionTypes {
    ADMIN_DASHBOARD_DATA_PENDING = "ADMIN_DASHBOARD_DATA_PENDING",
    ADMIN_DASHBOARD_DATA_SUCCESS = "ADMIN_DASHBOARD_DATA_SUCCESS",
    ADMIN_DASHBOARD_DATA_FAILED = "ADMIN_DASHBOARD_DATA_FAILED",
  }
  
  export default actionTypes;
  