enum actionTypes {
  GENERAL_DATA_PENDING = "GENERAL_DATA_PENDING",
  GENERAL_DATA_SUCCESS = "GENERAL_DATA_SUCCESS",
  GENERAL_DATA_FAILED = "GENERAL_DATA_SUCCESS",

  CONTACT_DATA_PENDING = "CONTACT_DATA_PENDING",
  CONTACT_DATA_SUCCESS = "CONTACT_DATA_SUCCESS ",
  CONTACT_DATA_FAILED = "CONTACT_DATA_FAILED",

  ADDRESS_DATA_PENDING = "ADDRESS_DATA_PENDING",
  ADDRESS_DATA_SUCCESS = "ADDRESS_DATA_SUCCESS",
  ADDRESS_DATA_FAILED = "ADDRESS_DATA_FAILED",
}
export default actionTypes;
