enum actionTypes {
  DASHBOARD_DATA_PENDING = "DASHBOARD_DATA_PENDING",
  DASHBOARD_DATA_SUCCESS = "DASHBOARD_DATA_SUCCESS",
  DASHBOARD_DATA_FAILED = "DASHBOARD_DATA_FAILED",
}

export default actionTypes;
